default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'user' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  port: <%= ENV['DB_PORT'] || '5432' %>

development:
  <<: *default
  database: test_cardiologs_development

test:
  <<: *default
  database: test_cardiologs_test

production:
  <<: *default
  database: test_cardiologs_production
  username: test_cardiologs
  password: <%= ENV["TEST_CARDIOLOGS_DATABASE_PASSWORD"] %>
